{{/*
SPDX-FileCopyrightText: 2026 Intel Corporation

SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "component-status.fullname" . }}-config
  labels:
    {{- include "component-status.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.componentStatus | nindent 4 }}
