---
# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apimappingconfig.edge-orchestrator.intel.com/v1
kind: APIMappingConfig
metadata:
  name: amc-opendmt-mps-openapi
  labels:
    configs.config.edge-orchestrator.intel.com: default
spec:
  specGenEnabled: true
  downloadConf:
    url: "https://api.swaggerhub.com/apis/rbheopenamt/mps/2.13.0/swagger.yaml"
    version: "2.13.0"
  mappings:
    - externalURI: /v1/projects/{projectName}/dm/amt/generalSettings/{guid}
      serviceURI: api/v1/amt/generalSettings/{guid}
    - externalURI: /v1/projects/{projectName}/dm/devices/{guid}
      serviceURI: api/v1/devices/{guid}
    
    # KVM-related endpoints
    - externalURI: /v1/projects/{projectName}/dm/devices/{guid}/kvm/redirect-token
      serviceURI: api/v1/authorize/redirection/{guid}
    - externalURI: /v1/projects/{projectName}/dm/devices/{guid}/kvm/features
      serviceURI: api/v1/amt/features/{guid}
  backend:
    service: "mps.orch-infra.svc.cluster.local"
    port: 3000
