# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apimappingconfig.edge-orchestrator.intel.com/v1
kind: APIMappingConfig
metadata:
  name: amc-infra-core-edge-infrastructure-manager-openapi-all-v2
  labels:
    configs.config.edge-orchestrator.intel.com: default
spec:
  specGenEnabled: true
  repoConf:
    url: "https://github.com/open-edge-platform/infra-core.git"
    tag: "apiv2/v0.0.1"
    specFilePath: "apiv2/api/openapi/openapi.yaml"
  mappings:
    - externalURI: /v2/projects/{projectName}/regions
      serviceURI: edge-infra.orchestrator.apis/v2/regions
    - externalURI: /v2/projects/{projectName}/regions/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/regions/{resourceId}
    - externalURI: /v2/projects/{projectName}/regions/{resourceId}/sites
      serviceURI: edge-infra.orchestrator.apis/v2/sites
    - externalURI: /v2/projects/{projectName}/regions/{resourceId}/sites/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/sites/{resourceId}
    - externalURI: /v2/projects/{projectName}/compute
      serviceURI: edge-infra.orchestrator.apis/v2/compute
    - externalURI: /v2/projects/{projectName}/compute/hosts
      serviceURI: edge-infra.orchestrator.apis/v2/compute/hosts
    - externalURI: /v2/projects/{projectName}/compute/hosts/summary
      serviceURI: edge-infra.orchestrator.apis/v2/hosts/summary
    - externalURI: /v2/projects/{projectName}/compute/hosts/register
      serviceURI: edge-infra.orchestrator.apis/v2/hosts/register
    - externalURI: /v2/projects/{projectName}/compute/hosts/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/hosts/{resourceId}
    - externalURI: /v2/projects/{projectName}/compute/hosts/{resourceId}/invalidate
      serviceURI: edge-infra.orchestrator.apis/v2/hosts/{resourceId}/invalidate
    - externalURI: /v2/projects/{projectName}/compute/hosts/{resourceId}/onboard
      serviceURI: edge-infra.orchestrator.apis/v2/hosts/{resourceId}/onboard
    - externalURI: /v2/projects/{projectName}/compute/hosts/{resourceId}/register
      serviceURI: edge-infra.orchestrator.apis/v2/hosts/{resourceId}/register
    - externalURI: /v2/projects/{projectName}/compute/instances
      serviceURI: edge-infra.orchestrator.apis/v2/instances
    - externalURI: /v2/projects/{projectName}/compute/instances/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/instances/{resourceId}
    - externalURI: /v2/projects/{projectName}/compute/instances/{resourceId}/invalidate
      serviceURI: edge-infra.orchestrator.apis/v2/instances/{resourceId}/invalidate
    - externalURI: /v2/projects/{projectName}/locations
      serviceURI: edge-infra.orchestrator.apis/v2/locations
    - externalURI: /v2/projects/{projectName}/compute/os
      serviceURI: edge-infra.orchestrator.apis/v2/operating_systems
    - externalURI: /v2/projects/{projectName}/compute/os/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/operating_systems/{resourceId}
    - externalURI: /v2/projects/{projectName}/compute/schedules
      serviceURI: edge-infra.orchestrator.apis/v2/schedules
    - externalURI: /v2/projects/{projectName}/compute/workloads
      serviceURI: edge-infra.orchestrator.apis/v2/workloads
    - externalURI: /v2/projects/{projectName}/compute/workloads/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/workloads/{resourceId}
    - externalURI: /v2/projects/{projectName}/compute/workloads/{resourceId}/members
      serviceURI: edge-infra.orchestrator.apis/v2/workload_members
    - externalURI: /v2/projects/{projectName}/compute/workloads/{resourceId}/members/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/workload_members/{resourceId}
    - externalURI: /v2/projects/{projectName}/providers
      serviceURI: edge-infra.orchestrator.apis/v2/providers
    - externalURI: /v2/projects/{projectName}/providers/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/providers/{resourceId}
    - externalURI: /v2/projects/{projectName}/schedules/single
      serviceURI: edge-infra.orchestrator.apis/v2/schedules/single
    - externalURI: /v2/projects/{projectName}/schedules/single/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/schedules/single/{resourceId}
    - externalURI: /v2/projects/{projectName}/schedules/repeated
      serviceURI: edge-infra.orchestrator.apis/v2/schedules/repeated
    - externalURI: /v2/projects/{projectName}/schedules/repeated/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/schedules/repeated/{resourceId}
    - externalURI: /v2/projects/{projectName}/telemetry/loggroups
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/groups/logs
    - externalURI: /v2/projects/{projectName}/telemetry/loggroups/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/groups/logs/{resourceId}
    - externalURI: /v2/projects/{projectName}/telemetry/loggroups/{resourceId}/logprofiles
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/profiles/logs
    - externalURI: /v2/projects/{projectName}/telemetry/loggroups/{resourceId}/logprofiles/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/profiles/logs/{resourceId}
    - externalURI: /v2/projects/{projectName}/telemetry/metricgroups
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/groups/metrics
    - externalURI: /v2/projects/{projectName}/telemetry/metricgroups/{resourceId}/metricprofiles
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/profiles/metrics
    - externalURI: /v2/projects/{projectName}/telemetry/metricgroups/{resourceId}/metricprofiles/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/profiles/metrics/{resourceId}
    - externalURI: /v2/projects/{projectName}/telemetry/metricgroups/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/telemetry/groups/metrics/{resourceId}
    - externalURI: /v2/projects/{projectName}/localAccounts
      serviceURI: edge-infra.orchestrator.apis/v2/localAccounts
    - externalURI: /v2/projects/{projectName}/localAccounts/{resourceId}
      serviceURI: edge-infra.orchestrator.apis/v2/localAccounts/{resourceId}
  backend:
    service: "apiv2-proxy.orch-infra.svc.cluster.local"
    port: 8080
