# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
{{- $registry := .Values.global.registry -}}
{{ if .Values.image.registry }}
  {{- $registry = .Values.image.registry -}}
{{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iam.fullname" . }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "iam.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "iam.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.global.tainted true }}
      tolerations:
      - key: nexus
        operator: Equal
        value: api
      {{- end }}
      serviceAccountName: {{ include "iam.serviceAccountName" . }}
      initContainers:
      - name: wait-for-job
        image: bitnami/kubectl
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "edge-orchestrator.intel.com CRD is available, waiting for CR..."
          echo "Waiting for CR 'apimappingconfigs.apimappingconfig.edge-orchestrator.intel.com' to be available..."
          until kubectl get apimappingconfigs.apimappingconfig.edge-orchestrator.intel.com; do
            echo "edge-orchestrator.intel.com CRD not found, waiting..."
            sleep 10
          done
          while true; do
            OUTPUT=$(kubectl get apimappingconfigs.apimappingconfig.edge-orchestrator.intel.com 2>&1)
            if echo "$OUTPUT" | grep -q "No resources found"; then
              echo "edge-orchestrator.intel.com CRD not found, waiting..."
              sleep 10
            else
              break
            fi
          done
      containers:
      - name: {{ include "iam.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        env:
        {{- if .Values.humanReadableLogs }}
        - name: HUMAN
        {{- end }}
        - name: APIGWCONFIG
          value: /etc/config/iam-config.yaml
        - name: LOG_LEVEL
          value: {{ .Values.logging.level }}
        volumeMounts:
        - mountPath: /etc/config
          name: {{ include "iam.fullname" . }}
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: {{ include "iam.fullname" . }}
          defaultMode: 0555
        name: {{ include "iam.fullname" . }}
