# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

---
{{- if .Values.traefikReverseProxy.middlewares.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: iam-nexus-api-gw-http
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  headers:
    customRequestHeaders:
      Host: svc-iam-nexus-api-gw.{{ .Release.Namespace }}.svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: iam-umbrella-api-docs-custom-headers
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  headers:
    customResponseHeaders:
      Content-Security-Policy: 'default-src ''self''; form-action ''self''; object-src
        ''none''; frame-ancestors ''none''; script-src ''self'' ''unsafe-eval'' https://app-service-proxy.kind.internal https://unpkg.com ''sha256-nUq7lWq2TvhAJygRXx0IgVibfT0kP3oKCUoE6kScJ7g='';
        style-src ''self'' ''unsafe-inline'' https://unpkg.com; img-src ''self'' data: https://unpkg.com https://validator.swagger.io; connect-src
        ''self'' https://keycloak.kind.internal wss://vnc.kind.internal https://app-service-proxy.kind.internal
        https://app-orch.kind.internal https://api.kind.internal
        https://metadata.kind.internal https://alerting-monitor.kind.internal
        https://orchestrator-license.kind.internal; upgrade-insecure-requests; block-all-mixed-content'
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: iam-umbrella-api-docs-mw-ext-secure-headers
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  chain:
    middlewares:
      - name: iam-umbrella-api-docs-custom-headers
      - name: secure-headers
{{- end }}
