# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iam.fullname" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{ default  .Release.Namespace .Values.global.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "iam.fullname" . }}
{{ end }}
