# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nexus-k8scert-secret-permission
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["nexus.com"]
  resources: ["datamodels"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["orgactivewatcher.edge-orchestrator.intel.com"]
  resources: ["orgactivewatchers", "orgactivewatchers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["project.edge-orchestrator.intel.com"]
  resources: ["projects", "projects/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["runtimefolder.edge-orchestrator.intel.com"]
  resources: ["runtimefolders", "runtimefolders/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["runtimeproject.edge-orchestrator.intel.com"]
  resources: ["runtimeprojects", "runtimeprojects/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["folder.edge-orchestrator.intel.com"]
  resources: ["folders", "folders/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["config.edge-orchestrator.intel.com"]
  resources: ["configs", "configs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["runtimeorg.edge-orchestrator.intel.com"]
  resources: ["runtimeorgs", "runtimeorgs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["apimappingconfig.edge-orchestrator.intel.com"]
  resources: ["apimappingconfigs", "apimappingconfigs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["projectwatcher.edge-orchestrator.intel.com"]
  resources: ["projectwatchers", "projectwatchers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["org.edge-orchestrator.intel.com"]
  resources: ["orgs", "orgs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["network.edge-orchestrator.intel.com"]
  resources: ["networks", "networks/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["orgwatcher.edge-orchestrator.intel.com"]
  resources: ["orgwatchers", "orgwatchers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["tenancy.edge-orchestrator.intel.com"]
  resources: ["multitenancies", "multitenancies/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["runtime.edge-orchestrator.intel.com"]
  resources: ["runtimes", "runtimes/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["projectactivewatcher.edge-orchestrator.intel.com"]
  resources: ["projectactivewatchers", "projectactivewatchers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nexus-k8scert-secret-permission
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: nexus-k8scert-secret-permission
  apiGroup: rbac.authorization.k8s.io
