# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: capi-variables
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
