# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
version: 25.2.1
appVersion: "25.2.1"
description: Initialization job for application-deployment-manager secrets
name: adm-secret
