# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: 2
enable-beta-ecosystems: true
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/auth-service"
      - "/cert-synchronizer"
      - "/keycloak-tenant-controller"
      - "nexus-api-gateway"
      - "tenancy-api-mapping"
      - "tenancy-datamodel"
      - "tenancy-manager"
      - "traefik-plugins"
    schedule:
      interval: "daily"
  # Enable version updates for Helm version
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/auth-service"
      - "/aws-sm-proxy"
      - "cert-synchronizer"
      - "/keycloak-tenant-controller/images"
    schedule:
      interval: "daily"
    reviewers:
      - "se-chris-thach"
      - "dmytroye"
