# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: 2
enable-beta-ecosystems: true
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/auth-service"
      - "/aws-sm-proxy"
    schedule:
      interval: "daily"
  # Enable version updates for Helm version
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/auth-service"
      - "/aws-sm-proxy"
    schedule:
      interval: "weekly"
    reviewers:
      - "se-chris-thach"
      - "dmytroye"
