# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: 2
enable-beta-ecosystems: true
updates:
  # Maintain Go modules
  - package-ecosystem: "gomod"
    directories: 
      - "/auth-service"
    schedule:
      interval: "daily"
  # Maintain Helm version
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "se-chris-thach"
      - "dmytroye"
