# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

# use ".root" instead of "$" when templating the job
{{- define "jobYaml" }}
{{- $jobName := printf "adm-secret-%s" .jobSuffix }}
{{- $secretNamespace := .secretNamespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: orch-platform
spec:
  template:
    spec:
      initContainers:
        - name: install-dependencies
          image: alpine:3.22.1
          command: ["/bin/sh", "-c"]
          args:
          - |
            set -e
            apk add --no-cache curl
            curl -L -o /shared/jq https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux64
            chmod +x /shared/jq
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
            env:
            {{- with .Values.httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ . }}
            {{- end }}
            {{- with .Values.noProxy }}
            - name: NO_PROXY
              value: {{ . }}
            {{- end }}
          volumeMounts:
          - name: shared
            mountPath: /shared
      containers:
        - name: adm-secret
          image: "alpine/kubectl:1.34.1"
          command: ["/bin/sh", "/tmp/bin/run.sh"]
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: script
              mountPath: /tmp/bin
            - name: shared
              mountPath: /usr/local/sbin
          env:
            - name: VAULT_KEYS
              valueFrom:
                secretKeyRef:
                  name: vault-keys
                  key: vault-keys
            - name: APP_GITEA_USER
              valueFrom:
                secretKeyRef:
                  name: app-gitea-credential
                  key: username
            - name: APP_GITEA_PASS
              valueFrom:
                secretKeyRef:
                  name: app-gitea-credential
                  key: password
            - name: CLUSTER_GITEA_USER
              valueFrom:
                secretKeyRef:
                  name: cluster-gitea-credential
                  key: username
            - name: CLUSTER_GITEA_PASS
              valueFrom:
                secretKeyRef:
                  name: cluster-gitea-credential
                  key: password
            - name: SEC_NAMESPACE
              value: {{ $secretNamespace }}
      restartPolicy: Never
      serviceAccountName: adm-secret
      volumes:
        - name: shared
          emptyDir: {}
        - name: script
          configMap:
            name: adm-secret
            defaultMode: 0755
        - name: orch-svc-token
          secret:
            secretName: orch-svc-token
  backoffLimit: 4
{{- end }}
{{- $jobSuffix := include "jobYaml" (dict "root" $) | toYaml | sha256sum | trunc 10 }}
{{- include "jobYaml" (dict "root" $ "jobSuffix" $jobSuffix "secretNamespace" .Values.secretNamespace) }}
