# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: adm-secret
  namespace: {{ .Values.secretNamespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
