# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adm-secret
subjects:
  - kind: ServiceAccount
    name: adm-secret
roleRef:
  kind: ClusterRole
  name: adm-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adm-secret
  namespace: {{ .Values.secretNamespace }}
subjects:
  - kind: ServiceAccount
    name: adm-secret
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: adm-secret
  apiGroup: rbac.authorization.k8s.io
