# SPDX-FileCopyrightText: 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
description: A Helm chart for Traefik extra objects.
name: traefik-extra-objects
version: 26.1.2
appVersion: "26.1.1"
