# SPDX-FileCopyrightText: 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iam.fullname" . }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "iam.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "iam.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.global.tainted true }}
      tolerations:
      - key: nexus
        operator: Equal
        value: api
      {{- end }}
      serviceAccountName: {{ include "iam.serviceAccountName" . }}
      containers:
      - name: {{ include "iam.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        command:
        - /usr/local/bin/tenancy-manager
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.postgres }}
        {{- if .Values.postgres.secrets }}
        envFrom:
        - secretRef:
            name: {{ .Values.postgres.secrets }}
        {{- end }}
        {{- end }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logging.level }}
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: tenancy-config
      restartPolicy: Always
