# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestrator-tenancy-role
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
rules:
  - apiGroups: ["orgactivewatcher.edge-orchestrator.intel.com"]
    resources: ["orgactivewatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["projectactivewatcher.edge-orchestrator.intel.com"]
    resources: ["projectactivewatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["orgwatcher.edge-orchestrator.intel.com"]
    resources: ["orgwatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["projectwatcher.edge-orchestrator.intel.com"]
    resources: ["projectwatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tenancy.edge-orchestrator.intel.com"]
    resources: ["multitenancies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtime.edge-orchestrator.intel.com"]
    resources: ["runtimes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimeorg.edge-orchestrator.intel.com"]
    resources: ["runtimeorgs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimefolder.edge-orchestrator.intel.com"]
    resources: ["runtimefolders"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimeproject.edge-orchestrator.intel.com"]
    resources: ["runtimeprojects"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "iam.serviceAccountName" . }}-permission
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
rules:
  - apiGroups: ["tenancy.edge-orchestrator.intel.com"]
    resources: ["multitenancies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["config.edge-orchestrator.intel.com"]
    resources: ["configs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtime.edge-orchestrator.intel.com"]
    resources: ["runtimes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["orgwatcher.edge-orchestrator.intel.com"]
    resources: ["orgwatchers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["projectwatcher.edge-orchestrator.intel.com"]
    resources: ["projectwatchers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["orgactivewatcher.edge-orchestrator.intel.com"]
    resources: ["orgactivewatchers"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["projectactivewatcher.edge-orchestrator.intel.com"]
    resources: ["projectactivewatchers"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["org.edge-orchestrator.intel.com"]
    resources: ["orgs"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["org.edge-orchestrator.intel.com"]
    resources: ["orgs/status"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["folder.edge-orchestrator.intel.com"]
    resources: ["folders"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["project.edge-orchestrator.intel.com"]
    resources: ["projects"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["project.edge-orchestrator.intel.com"]
    resources: ["projects/status"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["runtimefolder.edge-orchestrator.intel.com"]
    resources: ["runtimefolders"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["runtimeorg.edge-orchestrator.intel.com"]
    resources: ["runtimeorgs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["runtimeproject.edge-orchestrator.intel.com"]
    resources: ["runtimeprojects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "iam.serviceAccountName" . }}-permission
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "iam.serviceAccountName" . }}-permission
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-orchestrator.intel.com-read-rolebinding
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: edge-orchestrator.intel.com-read-role
  apiGroup: rbac.authorization.k8s.io
