# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

namespace: default

# cronjob configuration
schedule: "* * * * *"

# etcd configuration
etcdVersion: v3.5.19
hostCertsPath: "/var/lib/rancher/rke2/server/tls/etcd"

# Proxy configuration
proxy:
  enabled: false
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
