# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

# CAPI providers are deployed via CAPI operator and configured via its CRds
# the helmchart .spec is passed unmodified to the CRD .spec

# https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-operator/operator.cluster.x-k8s.io/CoreProvider/v1alpha2@v0.15.1
core:
  name: cluster-api
  namespace: capi-system
  spec:
    version: "v1.9.0"
    configSecret:
      namespace: capi-variables
      name: capi-variables

# https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-operator/operator.cluster.x-k8s.io/BootstrapProvider/v1alpha2@v0.15.1
bootstrap:
  name: rke2
  namespace: capr-system
  spec:
    version: v0.12.0
    configSecret:
      namespace: capi-variables
      name: capi-variables

# https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-operator/operator.cluster.x-k8s.io/ControlPlaneProvider/v1alpha2@v0.15.1
controlplane:
  name: rke2
  namespace: capr-system
  spec:
    version: v0.12.0
    configSecret:
      namespace: capi-variables
      name: capi-variables

# Configuration for enabling or disabling metrics
# For all CAPI providers
metrics:
  enabled: true