// Code generated by ent, DO NOT EDIT.

package tenancyevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldID, id))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldEventType, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldResourceType, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldResourceID, v))
}

// ResourceName applies equality check predicate on the "resource_name" field. It's identical to ResourceNameEQ.
func ResourceName(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldResourceName, v))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldOrgID, v))
}

// OrgName applies equality check predicate on the "org_name" field. It's identical to OrgNameEQ.
func OrgName(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldOrgName, v))
}

// FolderID applies equality check predicate on the "folder_id" field. It's identical to FolderIDEQ.
func FolderID(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldFolderID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContainsFold(FieldEventType, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContainsFold(FieldResourceType, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldResourceID, v))
}

// ResourceNameEQ applies the EQ predicate on the "resource_name" field.
func ResourceNameEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldResourceName, v))
}

// ResourceNameNEQ applies the NEQ predicate on the "resource_name" field.
func ResourceNameNEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldResourceName, v))
}

// ResourceNameIn applies the In predicate on the "resource_name" field.
func ResourceNameIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldResourceName, vs...))
}

// ResourceNameNotIn applies the NotIn predicate on the "resource_name" field.
func ResourceNameNotIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldResourceName, vs...))
}

// ResourceNameGT applies the GT predicate on the "resource_name" field.
func ResourceNameGT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldResourceName, v))
}

// ResourceNameGTE applies the GTE predicate on the "resource_name" field.
func ResourceNameGTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldResourceName, v))
}

// ResourceNameLT applies the LT predicate on the "resource_name" field.
func ResourceNameLT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldResourceName, v))
}

// ResourceNameLTE applies the LTE predicate on the "resource_name" field.
func ResourceNameLTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldResourceName, v))
}

// ResourceNameContains applies the Contains predicate on the "resource_name" field.
func ResourceNameContains(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContains(FieldResourceName, v))
}

// ResourceNameHasPrefix applies the HasPrefix predicate on the "resource_name" field.
func ResourceNameHasPrefix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasPrefix(FieldResourceName, v))
}

// ResourceNameHasSuffix applies the HasSuffix predicate on the "resource_name" field.
func ResourceNameHasSuffix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasSuffix(FieldResourceName, v))
}

// ResourceNameEqualFold applies the EqualFold predicate on the "resource_name" field.
func ResourceNameEqualFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEqualFold(FieldResourceName, v))
}

// ResourceNameContainsFold applies the ContainsFold predicate on the "resource_name" field.
func ResourceNameContainsFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContainsFold(FieldResourceName, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDIsNil applies the IsNil predicate on the "org_id" field.
func OrgIDIsNil() predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIsNull(FieldOrgID))
}

// OrgIDNotNil applies the NotNil predicate on the "org_id" field.
func OrgIDNotNil() predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotNull(FieldOrgID))
}

// OrgNameEQ applies the EQ predicate on the "org_name" field.
func OrgNameEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldOrgName, v))
}

// OrgNameNEQ applies the NEQ predicate on the "org_name" field.
func OrgNameNEQ(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldOrgName, v))
}

// OrgNameIn applies the In predicate on the "org_name" field.
func OrgNameIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldOrgName, vs...))
}

// OrgNameNotIn applies the NotIn predicate on the "org_name" field.
func OrgNameNotIn(vs ...string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldOrgName, vs...))
}

// OrgNameGT applies the GT predicate on the "org_name" field.
func OrgNameGT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldOrgName, v))
}

// OrgNameGTE applies the GTE predicate on the "org_name" field.
func OrgNameGTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldOrgName, v))
}

// OrgNameLT applies the LT predicate on the "org_name" field.
func OrgNameLT(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldOrgName, v))
}

// OrgNameLTE applies the LTE predicate on the "org_name" field.
func OrgNameLTE(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldOrgName, v))
}

// OrgNameContains applies the Contains predicate on the "org_name" field.
func OrgNameContains(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContains(FieldOrgName, v))
}

// OrgNameHasPrefix applies the HasPrefix predicate on the "org_name" field.
func OrgNameHasPrefix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasPrefix(FieldOrgName, v))
}

// OrgNameHasSuffix applies the HasSuffix predicate on the "org_name" field.
func OrgNameHasSuffix(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldHasSuffix(FieldOrgName, v))
}

// OrgNameIsNil applies the IsNil predicate on the "org_name" field.
func OrgNameIsNil() predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIsNull(FieldOrgName))
}

// OrgNameNotNil applies the NotNil predicate on the "org_name" field.
func OrgNameNotNil() predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotNull(FieldOrgName))
}

// OrgNameEqualFold applies the EqualFold predicate on the "org_name" field.
func OrgNameEqualFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEqualFold(FieldOrgName, v))
}

// OrgNameContainsFold applies the ContainsFold predicate on the "org_name" field.
func OrgNameContainsFold(v string) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldContainsFold(FieldOrgName, v))
}

// FolderIDEQ applies the EQ predicate on the "folder_id" field.
func FolderIDEQ(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldFolderID, v))
}

// FolderIDNEQ applies the NEQ predicate on the "folder_id" field.
func FolderIDNEQ(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldFolderID, v))
}

// FolderIDIn applies the In predicate on the "folder_id" field.
func FolderIDIn(vs ...uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldFolderID, vs...))
}

// FolderIDNotIn applies the NotIn predicate on the "folder_id" field.
func FolderIDNotIn(vs ...uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldFolderID, vs...))
}

// FolderIDGT applies the GT predicate on the "folder_id" field.
func FolderIDGT(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldFolderID, v))
}

// FolderIDGTE applies the GTE predicate on the "folder_id" field.
func FolderIDGTE(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldFolderID, v))
}

// FolderIDLT applies the LT predicate on the "folder_id" field.
func FolderIDLT(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldFolderID, v))
}

// FolderIDLTE applies the LTE predicate on the "folder_id" field.
func FolderIDLTE(v uuid.UUID) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldFolderID, v))
}

// FolderIDIsNil applies the IsNil predicate on the "folder_id" field.
func FolderIDIsNil() predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIsNull(FieldFolderID))
}

// FolderIDNotNil applies the NotNil predicate on the "folder_id" field.
func FolderIDNotNil() predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotNull(FieldFolderID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenancyEvent) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenancyEvent) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenancyEvent) predicate.TenancyEvent {
	return predicate.TenancyEvent(sql.NotPredicates(p))
}
