# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for metallb config.
name: metallb-config
version: 1.0.1
