# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

{{- $passwords := dict }}
{{- range $k, $v := .Values.databases }}
{{- $currentPassword := randAlphaNum 16 | nospace }}
{{- $_ := set $passwords $v.name $currentPassword}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.name }}-local-postgresql
  namespace: {{ $v.namespace }}
  labels:
    managed-by: edge-manageability-framework
stringData:
  PGUSER: "{{$v.namespace}}-{{ $v.name }}_user"
  PGPASSWORD: "{{ $currentPassword }}"
  PGDATABASE: "{{$v.namespace}}-{{ $v.name}}"
  PGHOST: "postgresql.orch-database"
  PGPORT: "5432"
---
# In cloud deployments, we create a separate secret that points to
# the reader endpoint which is load-balanced to multiple read replicas.
# There is no such reader endpoint provided for local Postgres yet,
# but we create this secret to provide a similar look-and-feel to the cloud deployments.
# It still points to the same PGHOST as the default read-write endpoint.
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.name }}-reader-local-postgresql
  namespace: {{ $v.namespace }}
  labels:
    managed-by: edge-manageability-framework
stringData:
  PGUSER: "{{$v.namespace}}-{{ $v.name }}_user"
  PGPASSWORD: "{{ $currentPassword }}"
  PGDATABASE: "{{$v.namespace}}-{{ $v.name}}"
  PGHOST: "postgresql.orch-database"
  PGPORT: "5432"
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  namespace:  {{ .Values.namespace }}
  labels:
    managed-by: edge-manageability-framework
stringData:
{{- $passwords|toYaml|nindent 2 }}
