# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    webhook:
      url: "http://{{ required "A valid proxy.name entry required!" .Values.proxy.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ required "A valid proxy.port entry required!" .Values.proxy.port }}/aws-secret?name={{ required "A valid smSecret entry required!" .Values.smSecret }}"
      result:
        jsonPath: "$.id_token"
