// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ControllerStatusColumns holds the columns for the "controller_status" table.
	ControllerStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "controller_name", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"in_progress", "completed", "error"}, Default: "in_progress"},
		{Name: "message", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ControllerStatusTable holds the schema information for the "controller_status" table.
	ControllerStatusTable = &schema.Table{
		Name:       "controller_status",
		Columns:    ControllerStatusColumns,
		PrimaryKey: []*schema.Column{ControllerStatusColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "controllerstatus_controller_name_resource_type_resource_id",
				Unique:  true,
				Columns: []*schema.Column{ControllerStatusColumns[1], ControllerStatusColumns[2], ControllerStatusColumns[3]},
			},
			{
				Name:    "controllerstatus_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{ControllerStatusColumns[2], ControllerStatusColumns[3]},
			},
		},
	}
	// FoldersColumns holds the columns for the "folders" table.
	FoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 253},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "org_folders", Type: field.TypeUUID},
	}
	// FoldersTable holds the schema information for the "folders" table.
	FoldersTable = &schema.Table{
		Name:       "folders",
		Columns:    FoldersColumns,
		PrimaryKey: []*schema.Column{FoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "folders_orgs_folders",
				Columns:    []*schema.Column{FoldersColumns[4]},
				RefColumns: []*schema.Column{OrgsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "folder_name_org_folders",
				Unique:  true,
				Columns: []*schema.Column{FoldersColumns[1], FoldersColumns[4]},
			},
		},
	}
	// OrgsColumns holds the columns for the "orgs" table.
	OrgsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 253},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// OrgsTable holds the schema information for the "orgs" table.
	OrgsTable = &schema.Table{
		Name:       "orgs",
		Columns:    OrgsColumns,
		PrimaryKey: []*schema.Column{OrgsColumns[0]},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 253},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "folder_projects", Type: field.TypeUUID},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_folders_projects",
				Columns:    []*schema.Column{ProjectsColumns[6]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_name_folder_projects",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[1], ProjectsColumns[6]},
			},
		},
	}
	// TenancyEventsColumns holds the columns for the "tenancy_events" table.
	TenancyEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "BIGSERIAL"}},
		{Name: "event_type", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeUUID},
		{Name: "resource_name", Type: field.TypeString, Size: 253},
		{Name: "org_id", Type: field.TypeUUID, Nullable: true},
		{Name: "org_name", Type: field.TypeString, Nullable: true, Size: 253},
		{Name: "folder_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TenancyEventsTable holds the schema information for the "tenancy_events" table.
	TenancyEventsTable = &schema.Table{
		Name:       "tenancy_events",
		Columns:    TenancyEventsColumns,
		PrimaryKey: []*schema.Column{TenancyEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenancyevent_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{TenancyEventsColumns[2], TenancyEventsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ControllerStatusTable,
		FoldersTable,
		OrgsTable,
		ProjectsTable,
		TenancyEventsTable,
	}
)

func init() {
	FoldersTable.ForeignKeys[0].RefTable = OrgsTable
	ProjectsTable.ForeignKeys[0].RefTable = FoldersTable
}
