# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.targetGroup }}
{{- if .Values.targetGroup.traefik }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: orch-gateway
  name: traefik-https
spec:
  serviceRef:
    name: traefik
    port: 443
  targetGroupARN: {{ .Values.targetGroup.traefik }}
{{- end }}
{{- if .Values.targetGroup.traefikGrpc }}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: orch-gateway
  name: traefik-grpc
spec:
  serviceRef:
    name: traefik
    port: 443
  targetGroupARN: {{ .Values.targetGroup.traefikGrpc }}
{{- end }}
{{- if .Values.targetGroup.argocd }}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: argocd
  name: argocd
spec:
  serviceRef:
    name: argocd-server
    port: 443
  targetGroupARN: {{ .Values.targetGroup.argocd }}
{{- end }}
{{- if .Values.targetGroup.nginx }}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: orch-boots
  name: ingress-nginx-controller
spec:
  serviceRef:
    name: ingress-nginx-controller
    port: 443
  targetGroupARN: {{ .Values.targetGroup.nginx }}
{{- end }}
{{- end }}
