# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: tenancy-manager
description: Multi Tenancy Manager
type: application
version: 0.1.7
appVersion: "1.1.3"
annotations: {}