apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secrets-config.fullname" . }}
  labels:
    {{- include "secrets-config.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
