# SPDX-FileCopyrightText: 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: keycloak-instance
description: Keycloak Operator deployment with realm configuration
type: application
version: 26.1.7
appVersion: "26.1.3"
annotations:
  # Keycloak upstream version information
  keycloak-upstream-version: "26.6.0"
  keycloak-upstream-keycloak-image: "quay.io/keycloak/keycloak:26.6.0"
  keycloak-config-cli-image: "docker.io/adorsys/keycloak-config-cli:6.4.0-26"
