# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rs-proxy.fullname" . }}
  labels:
    {{- include "rs-proxy.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rs-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rs-proxy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rs-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.service.port.https }}
              protocol: TCP
          livenessProbe:
              {{- toYaml .Values.probes | nindent 12 }}
            httpGet:
              path: /healthz
              port: {{ .Values.service.port.http }}
          readinessProbe:
              {{- toYaml .Values.probes | nindent 12 }}
            httpGet:
              path: /healthz
              port: {{ .Values.service.port.http }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/caddy
              readOnly: false
            - name: certs-https
              mountPath: /data-tls
              readOnly: true
            - name: caddy-certs
              mountPath: /data/caddy
            - name: caddy-config
              mountPath: /config/caddy
            - name: tmp
              mountPath: /tmp
          {{- if .Values.proxyTargetCA }}
            - name: certs
              mountPath: /data-ca
              readOnly: true
          {{- end }}
      volumes:
        - name: config
          secret:
            secretName: caddy-config
        - name: certs-https
          secret:
            secretName: tls-rs-proxy
            defaultMode: 0400 # This sets the file permission to read-only for the owner
        - name: caddy-certs
          emptyDir:
            sizeLimit: 500Mi
        - name: caddy-config
          emptyDir:
            sizeLimit: 500Mi
        - name: tmp
          emptyDir:
            sizeLimit: 500Mi
      {{- if .Values.proxyTargetCA }}
        - name: certs
          configMap:
            name: config-ca-cert
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
