# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.withReleaseServiceToken }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: caddy-config
spec:
  refreshInterval: {{ required "A valid refreshInterval entry required!" .Values.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}             # name of the SecretStore (or kind specified)
  target:
    name: caddy-config  # name of the k8s Secret to be created
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          # name of the configmap to pull in
          name: caddy-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: Caddyfile
            templateAs: Values
  data:
  # match this next value in the template
  - secretKey: token
    remoteRef:
      # secret name
      key: release-service-token
      # key name inside of secret
      property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: caddy-config-files
spec:
  refreshInterval: {{ required "A valid refreshInterval entry required!" .Values.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}             # name of the SecretStore (or kind specified)
  target:
    name: caddy-config-files  # name of the k8s Secret to be created
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          # name of the configmap to pull in
          name: caddy-config-files-tpl
          # here you define the keys that should be used as template
          items:
          - key: Caddyfile
            templateAs: Values
  data:
  # match this next value in the template
  - secretKey: token
    remoteRef:
      # secret name
      key: release-service-token
      # key name inside of secret
      property: token
{{- end }}
