---

# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-remapping-installer-role
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list"]
- apiGroups: ["apimappingconfig.edge-orchestrator.intel.com"]
  resources: ["apimappingconfigs"]
  verbs: ["get","list","create","update","patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-remapping-installer
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "iam.serviceAccountName" . }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: api-remapping-installer-role
  apiGroup: rbac.authorization.k8s.io

