// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ControllerStatus is the predicate function for controllerstatus builders.
type ControllerStatus func(*sql.Selector)

// Folder is the predicate function for folder builders.
type Folder func(*sql.Selector)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// TenancyEvent is the predicate function for tenancyevent builders.
type TenancyEvent func(*sql.Selector)
