// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/controllerstatus"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/predicate"
)

// ControllerStatusDelete is the builder for deleting a ControllerStatus entity.
type ControllerStatusDelete struct {
	config
	hooks    []Hook
	mutation *ControllerStatusMutation
}

// Where appends a list predicates to the ControllerStatusDelete builder.
func (_d *ControllerStatusDelete) Where(ps ...predicate.ControllerStatus) *ControllerStatusDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ControllerStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ControllerStatusDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ControllerStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(controllerstatus.Table, sqlgraph.NewFieldSpec(controllerstatus.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ControllerStatusDeleteOne is the builder for deleting a single ControllerStatus entity.
type ControllerStatusDeleteOne struct {
	_d *ControllerStatusDelete
}

// Where appends a list predicates to the ControllerStatusDelete builder.
func (_d *ControllerStatusDeleteOne) Where(ps ...predicate.ControllerStatus) *ControllerStatusDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ControllerStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{controllerstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ControllerStatusDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
