// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/controllerstatus"
)

// ControllerStatus is the model entity for the ControllerStatus schema.
type ControllerStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ControllerName holds the value of the "controller_name" field.
	ControllerName string `json:"controller_name,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID uuid.UUID `json:"resource_id,omitempty"`
	// Status holds the value of the "status" field.
	Status controllerstatus.Status `json:"status,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ControllerStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case controllerstatus.FieldID:
			values[i] = new(sql.NullInt64)
		case controllerstatus.FieldControllerName, controllerstatus.FieldResourceType, controllerstatus.FieldStatus, controllerstatus.FieldMessage:
			values[i] = new(sql.NullString)
		case controllerstatus.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case controllerstatus.FieldResourceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ControllerStatus fields.
func (_m *ControllerStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case controllerstatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case controllerstatus.FieldControllerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field controller_name", values[i])
			} else if value.Valid {
				_m.ControllerName = value.String
			}
		case controllerstatus.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case controllerstatus.FieldResourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value != nil {
				_m.ResourceID = *value
			}
		case controllerstatus.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = controllerstatus.Status(value.String)
			}
		case controllerstatus.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case controllerstatus.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ControllerStatus.
// This includes values selected through modifiers, order, etc.
func (_m *ControllerStatus) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ControllerStatus.
// Note that you need to call ControllerStatus.Unwrap() before calling this method if this ControllerStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ControllerStatus) Update() *ControllerStatusUpdateOne {
	return NewControllerStatusClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ControllerStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ControllerStatus) Unwrap() *ControllerStatus {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ControllerStatus is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ControllerStatus) String() string {
	var builder strings.Builder
	builder.WriteString("ControllerStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("controller_name=")
	builder.WriteString(_m.ControllerName)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ControllerStatusSlice is a parsable slice of ControllerStatus.
type ControllerStatusSlice []*ControllerStatus
