// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/controllerstatus"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/predicate"
)

// ControllerStatusUpdate is the builder for updating ControllerStatus entities.
type ControllerStatusUpdate struct {
	config
	hooks    []Hook
	mutation *ControllerStatusMutation
}

// Where appends a list predicates to the ControllerStatusUpdate builder.
func (_u *ControllerStatusUpdate) Where(ps ...predicate.ControllerStatus) *ControllerStatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetControllerName sets the "controller_name" field.
func (_u *ControllerStatusUpdate) SetControllerName(v string) *ControllerStatusUpdate {
	_u.mutation.SetControllerName(v)
	return _u
}

// SetNillableControllerName sets the "controller_name" field if the given value is not nil.
func (_u *ControllerStatusUpdate) SetNillableControllerName(v *string) *ControllerStatusUpdate {
	if v != nil {
		_u.SetControllerName(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ControllerStatusUpdate) SetResourceType(v string) *ControllerStatusUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ControllerStatusUpdate) SetNillableResourceType(v *string) *ControllerStatusUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ControllerStatusUpdate) SetResourceID(v uuid.UUID) *ControllerStatusUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ControllerStatusUpdate) SetNillableResourceID(v *uuid.UUID) *ControllerStatusUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ControllerStatusUpdate) SetStatus(v controllerstatus.Status) *ControllerStatusUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ControllerStatusUpdate) SetNillableStatus(v *controllerstatus.Status) *ControllerStatusUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ControllerStatusUpdate) SetMessage(v string) *ControllerStatusUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ControllerStatusUpdate) SetNillableMessage(v *string) *ControllerStatusUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ControllerStatusUpdate) SetUpdatedAt(v time.Time) *ControllerStatusUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ControllerStatusMutation object of the builder.
func (_u *ControllerStatusUpdate) Mutation() *ControllerStatusMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ControllerStatusUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ControllerStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ControllerStatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ControllerStatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ControllerStatusUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := controllerstatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ControllerStatusUpdate) check() error {
	if v, ok := _u.mutation.ControllerName(); ok {
		if err := controllerstatus.ControllerNameValidator(v); err != nil {
			return &ValidationError{Name: "controller_name", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.controller_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := controllerstatus.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := controllerstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ControllerStatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(controllerstatus.Table, controllerstatus.Columns, sqlgraph.NewFieldSpec(controllerstatus.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ControllerName(); ok {
		_spec.SetField(controllerstatus.FieldControllerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(controllerstatus.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(controllerstatus.FieldResourceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(controllerstatus.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(controllerstatus.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(controllerstatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{controllerstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ControllerStatusUpdateOne is the builder for updating a single ControllerStatus entity.
type ControllerStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ControllerStatusMutation
}

// SetControllerName sets the "controller_name" field.
func (_u *ControllerStatusUpdateOne) SetControllerName(v string) *ControllerStatusUpdateOne {
	_u.mutation.SetControllerName(v)
	return _u
}

// SetNillableControllerName sets the "controller_name" field if the given value is not nil.
func (_u *ControllerStatusUpdateOne) SetNillableControllerName(v *string) *ControllerStatusUpdateOne {
	if v != nil {
		_u.SetControllerName(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ControllerStatusUpdateOne) SetResourceType(v string) *ControllerStatusUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ControllerStatusUpdateOne) SetNillableResourceType(v *string) *ControllerStatusUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ControllerStatusUpdateOne) SetResourceID(v uuid.UUID) *ControllerStatusUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ControllerStatusUpdateOne) SetNillableResourceID(v *uuid.UUID) *ControllerStatusUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ControllerStatusUpdateOne) SetStatus(v controllerstatus.Status) *ControllerStatusUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ControllerStatusUpdateOne) SetNillableStatus(v *controllerstatus.Status) *ControllerStatusUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ControllerStatusUpdateOne) SetMessage(v string) *ControllerStatusUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ControllerStatusUpdateOne) SetNillableMessage(v *string) *ControllerStatusUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ControllerStatusUpdateOne) SetUpdatedAt(v time.Time) *ControllerStatusUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ControllerStatusMutation object of the builder.
func (_u *ControllerStatusUpdateOne) Mutation() *ControllerStatusMutation {
	return _u.mutation
}

// Where appends a list predicates to the ControllerStatusUpdate builder.
func (_u *ControllerStatusUpdateOne) Where(ps ...predicate.ControllerStatus) *ControllerStatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ControllerStatusUpdateOne) Select(field string, fields ...string) *ControllerStatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ControllerStatus entity.
func (_u *ControllerStatusUpdateOne) Save(ctx context.Context) (*ControllerStatus, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ControllerStatusUpdateOne) SaveX(ctx context.Context) *ControllerStatus {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ControllerStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ControllerStatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ControllerStatusUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := controllerstatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ControllerStatusUpdateOne) check() error {
	if v, ok := _u.mutation.ControllerName(); ok {
		if err := controllerstatus.ControllerNameValidator(v); err != nil {
			return &ValidationError{Name: "controller_name", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.controller_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := controllerstatus.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := controllerstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ControllerStatusUpdateOne) sqlSave(ctx context.Context) (_node *ControllerStatus, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(controllerstatus.Table, controllerstatus.Columns, sqlgraph.NewFieldSpec(controllerstatus.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ControllerStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, controllerstatus.FieldID)
		for _, f := range fields {
			if !controllerstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != controllerstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ControllerName(); ok {
		_spec.SetField(controllerstatus.FieldControllerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(controllerstatus.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(controllerstatus.FieldResourceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(controllerstatus.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(controllerstatus.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(controllerstatus.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ControllerStatus{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{controllerstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
