// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/controllerstatus"
)

// ControllerStatusCreate is the builder for creating a ControllerStatus entity.
type ControllerStatusCreate struct {
	config
	mutation *ControllerStatusMutation
	hooks    []Hook
}

// SetControllerName sets the "controller_name" field.
func (_c *ControllerStatusCreate) SetControllerName(v string) *ControllerStatusCreate {
	_c.mutation.SetControllerName(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *ControllerStatusCreate) SetResourceType(v string) *ControllerStatusCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ControllerStatusCreate) SetResourceID(v uuid.UUID) *ControllerStatusCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ControllerStatusCreate) SetStatus(v controllerstatus.Status) *ControllerStatusCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ControllerStatusCreate) SetNillableStatus(v *controllerstatus.Status) *ControllerStatusCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *ControllerStatusCreate) SetMessage(v string) *ControllerStatusCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *ControllerStatusCreate) SetNillableMessage(v *string) *ControllerStatusCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ControllerStatusCreate) SetUpdatedAt(v time.Time) *ControllerStatusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ControllerStatusCreate) SetNillableUpdatedAt(v *time.Time) *ControllerStatusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ControllerStatusMutation object of the builder.
func (_c *ControllerStatusCreate) Mutation() *ControllerStatusMutation {
	return _c.mutation
}

// Save creates the ControllerStatus in the database.
func (_c *ControllerStatusCreate) Save(ctx context.Context) (*ControllerStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ControllerStatusCreate) SaveX(ctx context.Context) *ControllerStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ControllerStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ControllerStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ControllerStatusCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := controllerstatus.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Message(); !ok {
		v := controllerstatus.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := controllerstatus.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ControllerStatusCreate) check() error {
	if _, ok := _c.mutation.ControllerName(); !ok {
		return &ValidationError{Name: "controller_name", err: errors.New(`ent: missing required field "ControllerStatus.controller_name"`)}
	}
	if v, ok := _c.mutation.ControllerName(); ok {
		if err := controllerstatus.ControllerNameValidator(v); err != nil {
			return &ValidationError{Name: "controller_name", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.controller_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "ControllerStatus.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := controllerstatus.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "ControllerStatus.resource_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ControllerStatus.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := controllerstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ControllerStatus.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "ControllerStatus.message"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ControllerStatus.updated_at"`)}
	}
	return nil
}

func (_c *ControllerStatusCreate) sqlSave(ctx context.Context) (*ControllerStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ControllerStatusCreate) createSpec() (*ControllerStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &ControllerStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(controllerstatus.Table, sqlgraph.NewFieldSpec(controllerstatus.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ControllerName(); ok {
		_spec.SetField(controllerstatus.FieldControllerName, field.TypeString, value)
		_node.ControllerName = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(controllerstatus.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(controllerstatus.FieldResourceID, field.TypeUUID, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(controllerstatus.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(controllerstatus.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(controllerstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ControllerStatusCreateBulk is the builder for creating many ControllerStatus entities in bulk.
type ControllerStatusCreateBulk struct {
	config
	err      error
	builders []*ControllerStatusCreate
}

// Save creates the ControllerStatus entities in the database.
func (_c *ControllerStatusCreateBulk) Save(ctx context.Context) ([]*ControllerStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ControllerStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ControllerStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ControllerStatusCreateBulk) SaveX(ctx context.Context) []*ControllerStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ControllerStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ControllerStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
