// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/controllerstatus"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/folder"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/org"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/project"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/schema"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/tenancyevent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	controllerstatusFields := schema.ControllerStatus{}.Fields()
	_ = controllerstatusFields
	// controllerstatusDescControllerName is the schema descriptor for controller_name field.
	controllerstatusDescControllerName := controllerstatusFields[0].Descriptor()
	// controllerstatus.ControllerNameValidator is a validator for the "controller_name" field. It is called by the builders before save.
	controllerstatus.ControllerNameValidator = controllerstatusDescControllerName.Validators[0].(func(string) error)
	// controllerstatusDescResourceType is the schema descriptor for resource_type field.
	controllerstatusDescResourceType := controllerstatusFields[1].Descriptor()
	// controllerstatus.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	controllerstatus.ResourceTypeValidator = controllerstatusDescResourceType.Validators[0].(func(string) error)
	// controllerstatusDescMessage is the schema descriptor for message field.
	controllerstatusDescMessage := controllerstatusFields[4].Descriptor()
	// controllerstatus.DefaultMessage holds the default value on creation for the message field.
	controllerstatus.DefaultMessage = controllerstatusDescMessage.Default.(string)
	// controllerstatusDescUpdatedAt is the schema descriptor for updated_at field.
	controllerstatusDescUpdatedAt := controllerstatusFields[5].Descriptor()
	// controllerstatus.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	controllerstatus.DefaultUpdatedAt = controllerstatusDescUpdatedAt.Default.(func() time.Time)
	// controllerstatus.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	controllerstatus.UpdateDefaultUpdatedAt = controllerstatusDescUpdatedAt.UpdateDefault.(func() time.Time)
	folderFields := schema.Folder{}.Fields()
	_ = folderFields
	// folderDescName is the schema descriptor for name field.
	folderDescName := folderFields[1].Descriptor()
	// folder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	folder.NameValidator = func() func(string) error {
		validators := folderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// folderDescCreatedAt is the schema descriptor for created_at field.
	folderDescCreatedAt := folderFields[2].Descriptor()
	// folder.DefaultCreatedAt holds the default value on creation for the created_at field.
	folder.DefaultCreatedAt = folderDescCreatedAt.Default.(func() time.Time)
	// folderDescUpdatedAt is the schema descriptor for updated_at field.
	folderDescUpdatedAt := folderFields[3].Descriptor()
	// folder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	folder.DefaultUpdatedAt = folderDescUpdatedAt.Default.(func() time.Time)
	// folder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	folder.UpdateDefaultUpdatedAt = folderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// folderDescID is the schema descriptor for id field.
	folderDescID := folderFields[0].Descriptor()
	// folder.DefaultID holds the default value on creation for the id field.
	folder.DefaultID = folderDescID.Default.(func() uuid.UUID)
	orgFields := schema.Org{}.Fields()
	_ = orgFields
	// orgDescName is the schema descriptor for name field.
	orgDescName := orgFields[1].Descriptor()
	// org.NameValidator is a validator for the "name" field. It is called by the builders before save.
	org.NameValidator = func() func(string) error {
		validators := orgDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// orgDescDescription is the schema descriptor for description field.
	orgDescDescription := orgFields[2].Descriptor()
	// org.DefaultDescription holds the default value on creation for the description field.
	org.DefaultDescription = orgDescDescription.Default.(string)
	// orgDescCreatedAt is the schema descriptor for created_at field.
	orgDescCreatedAt := orgFields[3].Descriptor()
	// org.DefaultCreatedAt holds the default value on creation for the created_at field.
	org.DefaultCreatedAt = orgDescCreatedAt.Default.(func() time.Time)
	// orgDescUpdatedAt is the schema descriptor for updated_at field.
	orgDescUpdatedAt := orgFields[4].Descriptor()
	// org.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	org.DefaultUpdatedAt = orgDescUpdatedAt.Default.(func() time.Time)
	// org.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	org.UpdateDefaultUpdatedAt = orgDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orgDescID is the schema descriptor for id field.
	orgDescID := orgFields[0].Descriptor()
	// org.DefaultID holds the default value on creation for the id field.
	org.DefaultID = orgDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[1].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = func() func(string) error {
		validators := projectDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[2].Descriptor()
	// project.DefaultDescription holds the default value on creation for the description field.
	project.DefaultDescription = projectDescDescription.Default.(string)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[4].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	tenancyeventFields := schema.TenancyEvent{}.Fields()
	_ = tenancyeventFields
	// tenancyeventDescEventType is the schema descriptor for event_type field.
	tenancyeventDescEventType := tenancyeventFields[1].Descriptor()
	// tenancyevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	tenancyevent.EventTypeValidator = tenancyeventDescEventType.Validators[0].(func(string) error)
	// tenancyeventDescResourceType is the schema descriptor for resource_type field.
	tenancyeventDescResourceType := tenancyeventFields[2].Descriptor()
	// tenancyevent.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	tenancyevent.ResourceTypeValidator = tenancyeventDescResourceType.Validators[0].(func(string) error)
	// tenancyeventDescResourceName is the schema descriptor for resource_name field.
	tenancyeventDescResourceName := tenancyeventFields[4].Descriptor()
	// tenancyevent.ResourceNameValidator is a validator for the "resource_name" field. It is called by the builders before save.
	tenancyevent.ResourceNameValidator = tenancyeventDescResourceName.Validators[0].(func(string) error)
	// tenancyeventDescOrgName is the schema descriptor for org_name field.
	tenancyeventDescOrgName := tenancyeventFields[6].Descriptor()
	// tenancyevent.OrgNameValidator is a validator for the "org_name" field. It is called by the builders before save.
	tenancyevent.OrgNameValidator = tenancyeventDescOrgName.Validators[0].(func(string) error)
	// tenancyeventDescCreatedAt is the schema descriptor for created_at field.
	tenancyeventDescCreatedAt := tenancyeventFields[8].Descriptor()
	// tenancyevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenancyevent.DefaultCreatedAt = tenancyeventDescCreatedAt.Default.(func() time.Time)
}
