// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/predicate"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/tenancyevent"
)

// TenancyEventUpdate is the builder for updating TenancyEvent entities.
type TenancyEventUpdate struct {
	config
	hooks    []Hook
	mutation *TenancyEventMutation
}

// Where appends a list predicates to the TenancyEventUpdate builder.
func (_u *TenancyEventUpdate) Where(ps ...predicate.TenancyEvent) *TenancyEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TenancyEventUpdate) SetEventType(v string) *TenancyEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableEventType(v *string) *TenancyEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *TenancyEventUpdate) SetResourceType(v string) *TenancyEventUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableResourceType(v *string) *TenancyEventUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TenancyEventUpdate) SetResourceID(v uuid.UUID) *TenancyEventUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableResourceID(v *uuid.UUID) *TenancyEventUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *TenancyEventUpdate) SetResourceName(v string) *TenancyEventUpdate {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableResourceName(v *string) *TenancyEventUpdate {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *TenancyEventUpdate) SetOrgID(v uuid.UUID) *TenancyEventUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableOrgID(v *uuid.UUID) *TenancyEventUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *TenancyEventUpdate) ClearOrgID() *TenancyEventUpdate {
	_u.mutation.ClearOrgID()
	return _u
}

// SetOrgName sets the "org_name" field.
func (_u *TenancyEventUpdate) SetOrgName(v string) *TenancyEventUpdate {
	_u.mutation.SetOrgName(v)
	return _u
}

// SetNillableOrgName sets the "org_name" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableOrgName(v *string) *TenancyEventUpdate {
	if v != nil {
		_u.SetOrgName(*v)
	}
	return _u
}

// ClearOrgName clears the value of the "org_name" field.
func (_u *TenancyEventUpdate) ClearOrgName() *TenancyEventUpdate {
	_u.mutation.ClearOrgName()
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *TenancyEventUpdate) SetFolderID(v uuid.UUID) *TenancyEventUpdate {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *TenancyEventUpdate) SetNillableFolderID(v *uuid.UUID) *TenancyEventUpdate {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *TenancyEventUpdate) ClearFolderID() *TenancyEventUpdate {
	_u.mutation.ClearFolderID()
	return _u
}

// Mutation returns the TenancyEventMutation object of the builder.
func (_u *TenancyEventUpdate) Mutation() *TenancyEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenancyEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenancyEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenancyEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenancyEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenancyEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := tenancyevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := tenancyevent.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceName(); ok {
		if err := tenancyevent.ResourceNameValidator(v); err != nil {
			return &ValidationError{Name: "resource_name", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.resource_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrgName(); ok {
		if err := tenancyevent.OrgNameValidator(v); err != nil {
			return &ValidationError{Name: "org_name", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.org_name": %w`, err)}
		}
	}
	return nil
}

func (_u *TenancyEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenancyevent.Table, tenancyevent.Columns, sqlgraph.NewFieldSpec(tenancyevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(tenancyevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(tenancyevent.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(tenancyevent.FieldResourceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(tenancyevent.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(tenancyevent.FieldOrgID, field.TypeUUID, value)
	}
	if _u.mutation.OrgIDCleared() {
		_spec.ClearField(tenancyevent.FieldOrgID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OrgName(); ok {
		_spec.SetField(tenancyevent.FieldOrgName, field.TypeString, value)
	}
	if _u.mutation.OrgNameCleared() {
		_spec.ClearField(tenancyevent.FieldOrgName, field.TypeString)
	}
	if value, ok := _u.mutation.FolderID(); ok {
		_spec.SetField(tenancyevent.FieldFolderID, field.TypeUUID, value)
	}
	if _u.mutation.FolderIDCleared() {
		_spec.ClearField(tenancyevent.FieldFolderID, field.TypeUUID)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenancyevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenancyEventUpdateOne is the builder for updating a single TenancyEvent entity.
type TenancyEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenancyEventMutation
}

// SetEventType sets the "event_type" field.
func (_u *TenancyEventUpdateOne) SetEventType(v string) *TenancyEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableEventType(v *string) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *TenancyEventUpdateOne) SetResourceType(v string) *TenancyEventUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableResourceType(v *string) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TenancyEventUpdateOne) SetResourceID(v uuid.UUID) *TenancyEventUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableResourceID(v *uuid.UUID) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *TenancyEventUpdateOne) SetResourceName(v string) *TenancyEventUpdateOne {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableResourceName(v *string) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *TenancyEventUpdateOne) SetOrgID(v uuid.UUID) *TenancyEventUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableOrgID(v *uuid.UUID) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *TenancyEventUpdateOne) ClearOrgID() *TenancyEventUpdateOne {
	_u.mutation.ClearOrgID()
	return _u
}

// SetOrgName sets the "org_name" field.
func (_u *TenancyEventUpdateOne) SetOrgName(v string) *TenancyEventUpdateOne {
	_u.mutation.SetOrgName(v)
	return _u
}

// SetNillableOrgName sets the "org_name" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableOrgName(v *string) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetOrgName(*v)
	}
	return _u
}

// ClearOrgName clears the value of the "org_name" field.
func (_u *TenancyEventUpdateOne) ClearOrgName() *TenancyEventUpdateOne {
	_u.mutation.ClearOrgName()
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *TenancyEventUpdateOne) SetFolderID(v uuid.UUID) *TenancyEventUpdateOne {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *TenancyEventUpdateOne) SetNillableFolderID(v *uuid.UUID) *TenancyEventUpdateOne {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *TenancyEventUpdateOne) ClearFolderID() *TenancyEventUpdateOne {
	_u.mutation.ClearFolderID()
	return _u
}

// Mutation returns the TenancyEventMutation object of the builder.
func (_u *TenancyEventUpdateOne) Mutation() *TenancyEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenancyEventUpdate builder.
func (_u *TenancyEventUpdateOne) Where(ps ...predicate.TenancyEvent) *TenancyEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenancyEventUpdateOne) Select(field string, fields ...string) *TenancyEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenancyEvent entity.
func (_u *TenancyEventUpdateOne) Save(ctx context.Context) (*TenancyEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenancyEventUpdateOne) SaveX(ctx context.Context) *TenancyEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenancyEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenancyEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenancyEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := tenancyevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := tenancyevent.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceName(); ok {
		if err := tenancyevent.ResourceNameValidator(v); err != nil {
			return &ValidationError{Name: "resource_name", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.resource_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrgName(); ok {
		if err := tenancyevent.OrgNameValidator(v); err != nil {
			return &ValidationError{Name: "org_name", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.org_name": %w`, err)}
		}
	}
	return nil
}

func (_u *TenancyEventUpdateOne) sqlSave(ctx context.Context) (_node *TenancyEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenancyevent.Table, tenancyevent.Columns, sqlgraph.NewFieldSpec(tenancyevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenancyEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenancyevent.FieldID)
		for _, f := range fields {
			if !tenancyevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenancyevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(tenancyevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(tenancyevent.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(tenancyevent.FieldResourceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(tenancyevent.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(tenancyevent.FieldOrgID, field.TypeUUID, value)
	}
	if _u.mutation.OrgIDCleared() {
		_spec.ClearField(tenancyevent.FieldOrgID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OrgName(); ok {
		_spec.SetField(tenancyevent.FieldOrgName, field.TypeString, value)
	}
	if _u.mutation.OrgNameCleared() {
		_spec.ClearField(tenancyevent.FieldOrgName, field.TypeString)
	}
	if value, ok := _u.mutation.FolderID(); ok {
		_spec.SetField(tenancyevent.FieldFolderID, field.TypeUUID, value)
	}
	if _u.mutation.FolderIDCleared() {
		_spec.ClearField(tenancyevent.FieldFolderID, field.TypeUUID)
	}
	_node = &TenancyEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenancyevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
