// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/tenancyevent"
)

// TenancyEvent is the model entity for the TenancyEvent schema.
type TenancyEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID uuid.UUID `json:"resource_id,omitempty"`
	// ResourceName holds the value of the "resource_name" field.
	ResourceName string `json:"resource_name,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID *uuid.UUID `json:"org_id,omitempty"`
	// OrgName holds the value of the "org_name" field.
	OrgName *string `json:"org_name,omitempty"`
	// FolderID holds the value of the "folder_id" field.
	FolderID *uuid.UUID `json:"folder_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenancyEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenancyevent.FieldOrgID, tenancyevent.FieldFolderID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case tenancyevent.FieldID:
			values[i] = new(sql.NullInt64)
		case tenancyevent.FieldEventType, tenancyevent.FieldResourceType, tenancyevent.FieldResourceName, tenancyevent.FieldOrgName:
			values[i] = new(sql.NullString)
		case tenancyevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tenancyevent.FieldResourceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenancyEvent fields.
func (_m *TenancyEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenancyevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tenancyevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case tenancyevent.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case tenancyevent.FieldResourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value != nil {
				_m.ResourceID = *value
			}
		case tenancyevent.FieldResourceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_name", values[i])
			} else if value.Valid {
				_m.ResourceName = value.String
			}
		case tenancyevent.FieldOrgID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				_m.OrgID = new(uuid.UUID)
				*_m.OrgID = *value.S.(*uuid.UUID)
			}
		case tenancyevent.FieldOrgName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_name", values[i])
			} else if value.Valid {
				_m.OrgName = new(string)
				*_m.OrgName = value.String
			}
		case tenancyevent.FieldFolderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field folder_id", values[i])
			} else if value.Valid {
				_m.FolderID = new(uuid.UUID)
				*_m.FolderID = *value.S.(*uuid.UUID)
			}
		case tenancyevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenancyEvent.
// This includes values selected through modifiers, order, etc.
func (_m *TenancyEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TenancyEvent.
// Note that you need to call TenancyEvent.Unwrap() before calling this method if this TenancyEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenancyEvent) Update() *TenancyEventUpdateOne {
	return NewTenancyEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenancyEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenancyEvent) Unwrap() *TenancyEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenancyEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenancyEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TenancyEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	builder.WriteString("resource_name=")
	builder.WriteString(_m.ResourceName)
	builder.WriteString(", ")
	if v := _m.OrgID; v != nil {
		builder.WriteString("org_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OrgName; v != nil {
		builder.WriteString("org_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FolderID; v != nil {
		builder.WriteString("folder_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenancyEvents is a parsable slice of TenancyEvent.
type TenancyEvents []*TenancyEvent
