// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/tenancyevent"
)

// TenancyEventCreate is the builder for creating a TenancyEvent entity.
type TenancyEventCreate struct {
	config
	mutation *TenancyEventMutation
	hooks    []Hook
}

// SetEventType sets the "event_type" field.
func (_c *TenancyEventCreate) SetEventType(v string) *TenancyEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *TenancyEventCreate) SetResourceType(v string) *TenancyEventCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *TenancyEventCreate) SetResourceID(v uuid.UUID) *TenancyEventCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetResourceName sets the "resource_name" field.
func (_c *TenancyEventCreate) SetResourceName(v string) *TenancyEventCreate {
	_c.mutation.SetResourceName(v)
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *TenancyEventCreate) SetOrgID(v uuid.UUID) *TenancyEventCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_c *TenancyEventCreate) SetNillableOrgID(v *uuid.UUID) *TenancyEventCreate {
	if v != nil {
		_c.SetOrgID(*v)
	}
	return _c
}

// SetOrgName sets the "org_name" field.
func (_c *TenancyEventCreate) SetOrgName(v string) *TenancyEventCreate {
	_c.mutation.SetOrgName(v)
	return _c
}

// SetNillableOrgName sets the "org_name" field if the given value is not nil.
func (_c *TenancyEventCreate) SetNillableOrgName(v *string) *TenancyEventCreate {
	if v != nil {
		_c.SetOrgName(*v)
	}
	return _c
}

// SetFolderID sets the "folder_id" field.
func (_c *TenancyEventCreate) SetFolderID(v uuid.UUID) *TenancyEventCreate {
	_c.mutation.SetFolderID(v)
	return _c
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_c *TenancyEventCreate) SetNillableFolderID(v *uuid.UUID) *TenancyEventCreate {
	if v != nil {
		_c.SetFolderID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenancyEventCreate) SetCreatedAt(v time.Time) *TenancyEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenancyEventCreate) SetNillableCreatedAt(v *time.Time) *TenancyEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenancyEventCreate) SetID(v int64) *TenancyEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TenancyEventMutation object of the builder.
func (_c *TenancyEventCreate) Mutation() *TenancyEventMutation {
	return _c.mutation
}

// Save creates the TenancyEvent in the database.
func (_c *TenancyEventCreate) Save(ctx context.Context) (*TenancyEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenancyEventCreate) SaveX(ctx context.Context) *TenancyEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenancyEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenancyEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenancyEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenancyevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenancyEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "TenancyEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := tenancyevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "TenancyEvent.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := tenancyevent.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "TenancyEvent.resource_id"`)}
	}
	if _, ok := _c.mutation.ResourceName(); !ok {
		return &ValidationError{Name: "resource_name", err: errors.New(`ent: missing required field "TenancyEvent.resource_name"`)}
	}
	if v, ok := _c.mutation.ResourceName(); ok {
		if err := tenancyevent.ResourceNameValidator(v); err != nil {
			return &ValidationError{Name: "resource_name", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.resource_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OrgName(); ok {
		if err := tenancyevent.OrgNameValidator(v); err != nil {
			return &ValidationError{Name: "org_name", err: fmt.Errorf(`ent: validator failed for field "TenancyEvent.org_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenancyEvent.created_at"`)}
	}
	return nil
}

func (_c *TenancyEventCreate) sqlSave(ctx context.Context) (*TenancyEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenancyEventCreate) createSpec() (*TenancyEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TenancyEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenancyevent.Table, sqlgraph.NewFieldSpec(tenancyevent.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(tenancyevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(tenancyevent.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(tenancyevent.FieldResourceID, field.TypeUUID, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.ResourceName(); ok {
		_spec.SetField(tenancyevent.FieldResourceName, field.TypeString, value)
		_node.ResourceName = value
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(tenancyevent.FieldOrgID, field.TypeUUID, value)
		_node.OrgID = &value
	}
	if value, ok := _c.mutation.OrgName(); ok {
		_spec.SetField(tenancyevent.FieldOrgName, field.TypeString, value)
		_node.OrgName = &value
	}
	if value, ok := _c.mutation.FolderID(); ok {
		_spec.SetField(tenancyevent.FieldFolderID, field.TypeUUID, value)
		_node.FolderID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenancyevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TenancyEventCreateBulk is the builder for creating many TenancyEvent entities in bulk.
type TenancyEventCreateBulk struct {
	config
	err      error
	builders []*TenancyEventCreate
}

// Save creates the TenancyEvent entities in the database.
func (_c *TenancyEventCreateBulk) Save(ctx context.Context) ([]*TenancyEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenancyEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenancyEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenancyEventCreateBulk) SaveX(ctx context.Context) []*TenancyEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenancyEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenancyEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
