# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-wait-{{ required "A valid secretName entry required!" .Values.secretName }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
