# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-wait-{{ required "A valid secretName entry required!" .Values.secretName }}
  namespace: {{ .Release.Namespace }}
