# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v2
name: tenancy-datamodel-init
description: Tenancy Datamodel
type: application
version: 0.1.5
appVersion: "1.1.4"
annotations: {}
home: tenancy-iam.intel.com
maintainers:
  - name: Tenancy-IAM Team
    email: tenancy-iam@intel.com

