# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: keycloak-tenant-controller-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: keycloak-tenant-controller-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---