# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: orch-secret-token
  namespace: orch-gateway
spec:
  entryPoints: # We listen to requests coming from ports 443
    - websecure
  routes:
    - match: {{ required "A valid releaseMatchHost entry required!" .Values.releaseMatchHost }}
      kind: Rule
      middlewares:
        - name: validate-jwt
      priority: 20
      services:
        - name: {{ include "token-file-server.fullname" . }}
          port: 8080
          scheme: http
          namespace: orch-secret
  tls:
    secretName: {{ required "A valid orchSecretName entry required!" .Values.orchSecretName }}
{{- if .Values.tlsOption }}
    options:
      name: {{ .Values.tlsOption }}
      namespace: orch-gateway
{{- end }}
