# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
server:
  address: ":443"
  httpPort: "8082"
  certPath: "/etc/cert/cert.pem"
  keyPath: "/etc/cert/key.pem"
enableNexusRuntime: true
