---
# SPDX-FileCopyrightText: 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v2
name: tenancy-datamodel
description: Tenancy Datamodel
type: application
version: 26.1.1
appVersion: "26.1.1"
annotations: {}
