# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oci-secret-creds
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}             # name of the SecretStore (or kind specified)
  target:
    name: oci-secret-creds  # name of the k8s Secret to be created
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      engineVersion: v2
      data:
        name: oci-repo
        url: {{ required "A valid ociUrl entry required!" .Values.ociUrl }}
        enableOCI: "true"
        insecure: "false"
        type: helm
        username: "someuser"
        password: "{{ `{{ .token }}` }}"
        ForceHttpBasicAuth: "false"
  data:
  # match this next value in the template
  - secretKey: token
    remoteRef:
      # secret name
      key: release-service-token
      # key name inside of secret
      property: token
