# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only from the specified namespace
      remoteNamespace: {{ required "A valid remoteNamespace entry required!" .Values.remoteNamespace }}
      server:
        url: "kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ .Release.Name }}
