# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: {{ .Values.controlplane.name }}
  namespace: {{ .Values.controlplane.namespace }}
spec:
  {{- toYaml .Values.controlplane.spec | nindent 2 }}
---
{{- if .Values.controlplane.additionalManifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.controlplane.additionalManifests.name }}
  namespace: {{ .Values.controlplane.additionalManifests.namespace | default .Values.controlplane.namespace }}
data:
  manifests: {{- toYaml .Values.controlplane.additionalManifests.manifests | nindent 2 }}
{{- end }}

