# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: {{ .Values.controlplane.name }}
  namespace: {{ .Values.controlplane.namespace }}
spec:
  {{- toYaml .Values.controlplane.spec | nindent 2 }}
---
{{- if .Values.controlplane.spec.additionalManifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.controlplane.spec.additionalManifests.name }}
  namespace: {{ .Values.controlplane.spec.additionalManifests.namespace | default .Values.controlplane.namespace }}
data:
  manifests: |
    {{- if .Values.controlplane.additionalManifests }}
    {{- toYaml .Values.controlplane.additionalManifests.manifests | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    ---
    {{- include "metricsservicetemplate" (dict "name" (printf "%s-%s" "controlplane" .Values.controlplane.name) "namespace" .Values.controlplane.namespace ) | nindent 4 }}
        selector:
          cluster.x-k8s.io/provider: control-plane-{{ .Values.bootstrap.name }}
    ---
    {{- include "metricsservicemonitortemplate" (dict "name" (printf "%s-%s" "controlplane" .Values.controlplane.name) "namespace" .Values.controlplane.namespace) | nindent 4 }}
    {{- end }}
{{- end }}

