# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: {{ .Values.core.name }}
  namespace: {{ .Values.core.namespace }}
spec:
  {{- toYaml .Values.core.spec | nindent 2 }}
---
{{- if .Values.core.additionalManifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.core.additionalManifests.name }}
  namespace: {{ .Values.core.additionalManifests.namespace | default .Values.core.namespace }}
data:
  manifests: {{- toYaml .Values.core.additionalManifests.manifests | nindent 2 }}
{{- end }}
