# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: {{ .Values.core.name }}
  namespace: {{ .Values.core.namespace }}
spec:
  {{- toYaml .Values.core.spec | nindent 2 }}
---
{{- if .Values.core.spec.additionalManifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.core.spec.additionalManifests.name }}
  namespace: {{ .Values.core.spec.additionalManifests.namespace | default .Values.core.namespace }}
data:
  manifests: |
    {{- if .Values.core.additionalManifests }}
    {{- toYaml .Values.core.additionalManifests.manifests | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    ---
    {{- include "metricsservicetemplate" (dict "name" (printf "%s-%s" "core" .Values.core.name) "namespace" .Values.core.namespace ) | nindent 4 }}
        selector:
          cluster.x-k8s.io/provider: cluster-api
    ---
    {{- include "metricsservicemonitortemplate" (dict "name" (printf "%s-%s" "core" .Values.core.name) "namespace" .Values.core.namespace) | nindent 4 }}
    {{- end }}
{{- end }}