// Code generated by ent, DO NOT EDIT.

package controllerstatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/open-edge-platform/orch-utils/tenancy-manager/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLTE(FieldID, id))
}

// ControllerName applies equality check predicate on the "controller_name" field. It's identical to ControllerNameEQ.
func ControllerName(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldControllerName, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldResourceType, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldResourceID, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldMessage, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldUpdatedAt, v))
}

// ControllerNameEQ applies the EQ predicate on the "controller_name" field.
func ControllerNameEQ(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldControllerName, v))
}

// ControllerNameNEQ applies the NEQ predicate on the "controller_name" field.
func ControllerNameNEQ(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldControllerName, v))
}

// ControllerNameIn applies the In predicate on the "controller_name" field.
func ControllerNameIn(vs ...string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldControllerName, vs...))
}

// ControllerNameNotIn applies the NotIn predicate on the "controller_name" field.
func ControllerNameNotIn(vs ...string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldControllerName, vs...))
}

// ControllerNameGT applies the GT predicate on the "controller_name" field.
func ControllerNameGT(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGT(FieldControllerName, v))
}

// ControllerNameGTE applies the GTE predicate on the "controller_name" field.
func ControllerNameGTE(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGTE(FieldControllerName, v))
}

// ControllerNameLT applies the LT predicate on the "controller_name" field.
func ControllerNameLT(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLT(FieldControllerName, v))
}

// ControllerNameLTE applies the LTE predicate on the "controller_name" field.
func ControllerNameLTE(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLTE(FieldControllerName, v))
}

// ControllerNameContains applies the Contains predicate on the "controller_name" field.
func ControllerNameContains(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldContains(FieldControllerName, v))
}

// ControllerNameHasPrefix applies the HasPrefix predicate on the "controller_name" field.
func ControllerNameHasPrefix(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldHasPrefix(FieldControllerName, v))
}

// ControllerNameHasSuffix applies the HasSuffix predicate on the "controller_name" field.
func ControllerNameHasSuffix(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldHasSuffix(FieldControllerName, v))
}

// ControllerNameEqualFold applies the EqualFold predicate on the "controller_name" field.
func ControllerNameEqualFold(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEqualFold(FieldControllerName, v))
}

// ControllerNameContainsFold applies the ContainsFold predicate on the "controller_name" field.
func ControllerNameContainsFold(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldContainsFold(FieldControllerName, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldContainsFold(FieldResourceType, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v uuid.UUID) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLTE(FieldResourceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldStatus, vs...))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldContainsFold(FieldMessage, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ControllerStatus) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ControllerStatus) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ControllerStatus) predicate.ControllerStatus {
	return predicate.ControllerStatus(sql.NotPredicates(p))
}
