{{- define "certificate-file-server.edge-node-installer" -}}
{{- $config := .Values.infraConfig | default dict }}
{{- $gatewayCert := "" }}
{{- $bootsCert := "" }}
{{- if .Values.orchSecretName }}
{{- $secret := (lookup "v1" "Secret" "orch-gateway" .Values.orchSecretName) }}
{{- if $secret }}
{{- $gatewayCert = index $secret.data "ca.crt" }}
{{- $bootsCert = index $secret.data "boots-ca.crt" | default "" }}
{{- end }}
{{- end }}
#!/bin/bash

# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# 
# Edge Node Installer - Curated Version
# Generated by Orchestrator with pre-configured values

set -euo pipefail

# ============================================================================
# CONFIGURATION (Pre-configured by Orchestrator)
# ============================================================================

# Proxy Configuration
{{- if index $config "enProxyHTTP" }}
EN_PROXY_HTTP="{{ index $config "enProxyHTTP" }}"
EN_PROXY_HTTPS="{{ index $config "enProxyHTTPS" | default (index $config "enProxyHTTP") }}"
{{- else }}
EN_PROXY_HTTP=""
EN_PROXY_HTTPS=""
{{- end }}
{{- if index $config "enProxyFTP" }}
EN_PROXY_FTP="{{ index $config "enProxyFTP" }}"
{{- else }}
EN_PROXY_FTP=""
{{- end }}
{{- if index $config "enProxySocks" }}
EN_PROXY_SOCKS="{{ index $config "enProxySocks" }}"
{{- else }}
EN_PROXY_SOCKS=""
{{- end }}
{{- if index $config "enProxyNoProxy" }}
EN_PROXY_NO_PROXY="{{ index $config "enProxyNoProxy" }}"
{{- else }}
EN_PROXY_NO_PROXY=""
{{- end }}

# Orchestrator Services
FILE_SERVER="{{ index $config "orchFileServer" }}"
REGISTRY="{{ index $config "orchRegistry" }}"
RPS_HOST="{{ index $config "orchRPSHost" }}"
KEYCLOAK="{{ index $config "orchKeycloak" }}"
RELEASE="{{ index $config "orchRelease" }}"
ORCH_CLUSTER="{{ index $config "orchCluster" }}"
ORCH_INFRA="{{ index $config "orchInfra" }}"
ORCH_KEYCLOAK="{{ index $config "orchKeycloak" }}"
ORCH_RELEASE="{{ index $config "orchRelease" }}"
ORCH_DEVICE_MANAGER="{{ index $config "orchDeviceManager" }}"
ORCH_APT_SRC_PROXY_PORT="{{ index $config "orchAptSrcProxyPort" | default "60444" }}"

# Edge Node Configuration
EN_SERVICE_CLIENTS="{{ index $config "enServiceClients" }}"
EN_OUTBOUND_CLIENTS="{{ index $config "enOutboundClients" | default " " }}"
EN_METRICS_ENABLED="{{ index $config "enMetricsEnabled" | default "false" }}"
EN_TOKEN_CLIENTS="{{ index $config "enTokenClients" }}"

# Registry and Repository
REGISTRY_SERVICE="{{ index $config "registryService" }}"
EN_DEBIAN_PACKAGES_REPO="{{ index $config "enDebianPackagesRepo" }}"
EN_FILES_RS_ROOT="{{ index $config "enFilesRsRoot" }}"
MANIFEST_REGISTRY="{{ index $config "registryService" }}"
MANIFEST_REPO="{{ index $config "enManifestRepo" }}"
MANIFEST_TAG="{{ index $config "enAgentManifestTag" }}"
MANIFEST_FILE="ena-manifest.yaml"

# Release Service
RS_TYPE="{{ index $config "rsType" | default "no-auth" }}"

# System Configuration  
KERNEL_CONFIG_OVER_COMMIT_MEMORY="{{ index $config "systemConfigVmOverCommitMemory" | default "1" }}"
KERNEL_CONFIG_KERNEL_PANIC="{{ index $config "systemConfigKernelPanic" | default "10" }}"
KERNEL_CONFIG_PANIC_ON_OOPS="{{ index $config "systemConfigKernelPanicOnOops" | default "1" }}"
KERNEL_CONFIG_MAX_USER_INSTANCE="{{ index $config "systemConfigFsInotifyMaxUserInstances" | default "8192" }}"

# NTP Server
NTP_SERVER="{{ index $config "ntpServer" | default "ntp1.server.org,ntp2.server.org" }}"

# Onboarding Manager
OM_SVC="{{ index $config "omSvc" }}"
OM_STREAM_SVC="{{ index $config "omStreamSvc" }}"

# CA Certificates (Base64 encoded)
GATEWAY_CA_CERT_B64="{{ $gatewayCert }}"
BOOTS_CA_CERT_B64="{{ $bootsCert }}"

# Firewall Rules
FW_REQ_RULES='{{ index $config "firewallReqAllow" | default "[]" }}'
FW_CFG_RULES='{{ index $config "firewallCfgAllow" | toJson | default "[]" }}'

# Agent versions (will be populated from manifest)
DEVICE_DISCOVERY_VERSION=""
NODE_AGENT_VERSION=""
PLATFORM_MANAGEABILITY_VERSION=""
PLATFORM_TELEMETRY_VERSION=""
CADDY_VERSION=""
APT_DISTRO=""

# ============================================================================
# INSTALLATION FUNCTIONS AND LOGIC
# ============================================================================

{{- $scriptContent := .Files.Get "scripts/edge-node-installer.sh" -}}
{{- $lines := splitList "\n" $scriptContent -}}
{{- range $index, $line := $lines -}}
{{- if ge $index 16 -}}
{{ $line }}
{{- end -}}
{{- end -}}
{{- end -}}
