# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "certificate-file-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  Caddyfile: |-
    # The Caddyfile is an easy way to configure your Caddy web server.
    #
    :{{ required "A valid service.port entry required!" .Values.service.port }}

    # Handle /boots path for CA certificates
    route /boots* {
      uri strip_prefix /boots
      root * {{ required "A valid rootFolder entry required!" .Values.rootFolder }}
      file_server
    }

    # Handle /installer path for installer script
    route /installer* {
      uri strip_prefix /installer
      root * {{ required "A valid rootFolder entry required!" .Values.rootFolder }}installer/
      file_server
    }

    # Default route for root path
    route {
      root * {{ required "A valid rootFolder entry required!" .Values.rootFolder }}
      file_server
    }

    # Refer to the Caddy docs for more information:
    # https://caddyserver.com/docs/caddyfile
  edge-node-installer.sh: |-
{{- include "certificate-file-server.edge-node-installer" . | nindent 4 }}
