---

# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

{{- $registry := .Values.global.registry -}}
{{ if .Values.image.registry }}
  {{- $registry = .Values.image.registry -}}
{{ end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "iam.fullname" . }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 6
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      activeDeadlineSeconds: 600
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "iam.serviceAccountName" . }}
      restartPolicy: Never
      initContainers:
      - name: job-wait-for-tenancy-crds
        image: alpine/kubectl:1.34.1
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        command: ["/bin/sh", "-c"]
        args:
        - |
            set -e
            echo "Waiting for Tenant CRDs to be available..."
            for CRD in "orgs.org.edge-orchestrator.intel.com" \
                      "orgwatchers.orgwatcher.edge-orchestrator.intel.com" \
                      "orgactivewatchers.orgactivewatcher.edge-orchestrator.intel.com" \
                      "runtimeorgs.runtimeorg.edge-orchestrator.intel.com" \
                      "projects.project.edge-orchestrator.intel.com" \
                      "projectwatchers.projectwatcher.edge-orchestrator.intel.com" \
                      "projectactivewatchers.projectactivewatcher.edge-orchestrator.intel.com" \
                      "runtimeprojects.runtimeproject.edge-orchestrator.intel.com"; do
              echo "Checking for CRD: $CRD"
                until kubectl get crd $CRD; do
                  echo "CRD $CRD not found, waiting..."
                  sleep 30
                done
              echo "CRD $CRD is available."
            done
            echo "Checking for KTC pod existence"
            until kubectl get po -l app=keycloak-tenant-controller-pod -A; do
              echo "KTC pod not found, waiting..."
              sleep 30
            done
            echo "KTC pod found. Checking for KTC status"
            kubectl wait --for=condition=Ready po -l app=keycloak-tenant-controller-pod -A
            echo "KTC is running. Exiting init container."
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        # image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        image: localhost:5000/tenancy-init:25.2.1
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--org={{ .Values.tenant.orgName }}"
          - "--project={{ .Values.tenant.projectName }}"
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
