# SPDX-FileCopyrightText: 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
description: A Helm chart for kyverno Traefik policies.
name: kyverno-traefik-policy
version: 26.0.1
appVersion: "26.0.1"
