# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-rewriter-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-rewriter-role
subjects:
- kind: ServiceAccount
  name: sa-cert-rewriter
  namespace: orch-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-rewriter-role
  namespace: orch-gateway
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get", "list", "watch", "create", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cert-rewriter
  namespace: orch-gateway
