# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

{{- if .Values.matchClusterLabels }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "fleet-cluster-es"
spec:
  externalSecretName: {{ .Release.Name }}
  {{- with .Values.matchClusterLabels }}
  namespaceSelector:
    matchLabels:
  {{- toYaml . | nindent 6 }}
  {{- end }}
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: fleet-cluster-ss
      kind: ClusterSecretStore
    refreshInterval: "180s"
    target:
      name: {{ .Release.Name }}
      creationPolicy: 'Owner'
      deletionPolicy: 'Retain'
      template:
        engineVersion: v2
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
        data:
          cacerts: "{{ `{{ .cert }}` }}"
    data:
      - secretKey: cert
        remoteRef:
          key: tls-rs-proxy
          property: ca.crt
{{- end }}
