# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.matchClusterLabels }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fleet-cluster-ss
spec:
  provider:
    kubernetes:
        auth:
          serviceAccount:
            name: default
        remoteNamespace: {{ required "A valid remoteNamespace entry required!" .Values.remoteNamespace }}
        server:
          caProvider:
            key: ca.crt
            name: kube-root-ca.crt
            type: ConfigMap
            namespace: {{ required "A valid remoteNamespace entry required!" .Values.remoteNamespace }}
          url: "kubernetes.default"
  {{- with .Values.matchClusterLabels }}
  conditions:
    - namespaceSelector:
        matchLabels:
  {{- toYaml . | nindent 10 }}
  {{- end }}
{{- end }}
