# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {{- tpl (toYaml .Values.operator.annotations) . | nindent 4 }}
  labels:
    helm.sh/chart: {{ include "keycloak-operator.chart" . }}
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ include "keycloak-operator.upstreamVersion" . | quote }}
    app.kubernetes.io/managed-by: quarkus
  name: keycloak-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
  template:
    metadata:
      annotations: {{- tpl (toYaml .Values.operator.annotations) . | nindent 8 }}
      labels:
        app.kubernetes.io/name: keycloak-operator
        app.kubernetes.io/version: {{ include "keycloak-operator.upstreamVersion" . | quote }}
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext: {{- toYaml .Values.operator.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      containers:
        - name: {{ .Values.operator.container.name }}
          image: {{ tpl .Values.operator.image . }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          securityContext: {{- toYaml .Values.operator.container.securityContext | nindent 12 }}
          ports: {{- toYaml .Values.operator.container.ports | nindent 12 }}
          env: {{- tpl (toYaml .Values.operator.container.env) . | nindent 12 }}
          livenessProbe: {{- toYaml .Values.operator.container.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.operator.container.readinessProbe | nindent 12 }}
          startupProbe: {{- toYaml .Values.operator.container.startupProbe | nindent 12 }}
          resources: {{- toYaml .Values.operator.container.resources | nindent 12 }}
          volumeMounts: {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes: {{- toYaml .Values.volumes | nindent 8 }}
