# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

# Dictionary of namespaces with a special value indicating if they should be labeled.
# - name: "ns-one"
#   labels:
#     any: label
#     goes: here
# - name: "ns-two"
#   labels:
#     istio-injection: enabled
namespaces: []
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
