# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-webhook
  namespace: kube-system
spec:
  secretName: vpa-tls-certs
  duration: 720h0m0s # 30 days
  renewBefore: 168h0m0s # 7 days
  subject:
    organizations:
      - Intel Corporation
    countries:
      - US
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    - vpa-webhook.kube-system.svc
  issuerRef:
    name: orchestrator-selfsigned-issuer
    kind: ClusterIssuer
