# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ required "A valid targetSecretName entry required!" .Values.targetSecretName }}
spec:
  refreshInterval: {{ required "A valid refreshInterval entry required!" .Values.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}             # name of the SecretStore (or kind specified)
  target:
    name: {{ required "A valid targetSecretName entry required!" .Values.targetSecretName }} # name of the k8s Secret to be created
    template:
      engineVersion: v2
      {{- if .Values.type }}
      type: {{ .Values.type }}
      {{- end }}
      data:
        # Take the target name if one is set or source name for the newly created secret
        {{ range .Values.keyName }}
        {{ or .target .source }}: {{ printf "\"{{ .%s }}\"" (.source | replace "." "_" | replace "-" "_") }}
        {{ end }}
  data:
    # match this next value in the template
    {{ range .Values.keyName }}
    - secretKey: {{ .source | replace "." "_" | replace "-" "_" }}
      remoteRef:
        # secret name
        key: {{ required "A valid sourceSecretName entry required!" $.Values.sourceSecretName }}
        # key name inside of secret
        property: {{ .source }}
    {{ end }}