# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
data:
  squid.conf: |
    http_port {{ .Values.service.port }}

    logfile_rotate 0
    access_log stdio:/proc/self/fd/1
    cache_log stdio:/proc/self/fd/1

    pid_filename none
    visible_hostname squid-proxy

    # Define ACLs for pre-approved URLs
    acl allowed_domains dstdomain {{ .Values.allowedDomains }}
    http_access allow allowed_domains

    # Define ACLs for Sentinel Licensing URLs
    acl sentinel dstdomain {{ .Values.sentinelDomains }}
    http_access allow sentinel
    cache deny sentinel
    request_header_add  Cache-Control "no-store" sentinel

    # Define ACLs for APT/PPA URLs
    acl apt dstdomain {{ .Values.aptDomains }}
    http_access allow apt

    # Define ACLs for Debian URLs
    acl debian dstdomain {{ .Values.debianDomains }}
    http_access allow debian

    # Deny all other traffic
    http_access deny all

    # Other Squid settings...
    cache deny all
    forwarded_for delete
    via off

    {{- if  ne .Values.httpsProxy "" }}
    # Specify the parent proxy (corporate proxy)
    cache_peer {{ include "squid-proxy.addressFromProxyString" . }} parent {{ include "squid-proxy.portFromProxyString" . }} 0 no-query default

    {{- if  ne .Values.noPeerProxyDomains "" }}
    # Define an ACL for the domains to be excluded from the peer proxy
    acl no_peer_domain dstdomain {{ .Values.noPeerProxyDomains }}

    # Define an ACL for all other requests
    acl all_peer_requests src all

    # Send requests for the excluded domain directly
    cache_peer_access {{ include "squid-proxy.addressFromProxyString" . }} deny no_peer_domain

    # Send all other requests to the peer proxy
    cache_peer_access {{ include "squid-proxy.addressFromProxyString" . }} allow all_peer_requests

    # Allow direct access to the excluded domain
    always_direct allow no_peer_domain
    {{- end }}

    # Never direct - always use the parent proxy
    never_direct allow all
    {{- end }}
