# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-wait-{{ required "A valid statefulsetName entry required!" .Values.statefulsetName }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: statefulset-wait-{{ required "A valid statefulsetName entry required!" .Values.statefulsetName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: statefulset-wait-{{ required "A valid statefulsetName entry required!" .Values.statefulsetName }}
  apiGroup: rbac.authorization.k8s.io
