# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-wait-{{ required "A valid statefulsetName entry required!" .Values.statefulsetName }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "watch", "list"]
