# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefulset-wait-{{ required "A valid statefulsetName entry required!" .Values.statefulsetName }}
  namespace: {{ .Release.Namespace }}
