# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-wait-{{ required "A valid jobPrefix entry required!" .Values.jobPrefix }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: job-wait-{{ required "A valid jobPrefix entry required!" .Values.jobPrefix }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: job-wait-{{ required "A valid jobPrefix entry required!" .Values.jobPrefix }}
  apiGroup: rbac.authorization.k8s.io
