# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-wait-{{ required "A valid jobPrefix entry required!" .Values.jobPrefix }}
  namespace: {{ .Release.Namespace }}
