# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Update Auto-Merge PRs

# On push to the main branch, update any branches that are out of date and have auto-merge enabled. If the branch is
# currently out of date, it must be first manually updated and then will be kept up to date on future runs.
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Auto-Update-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/auto-update@4081c5bdc34560b58288a010318054e63e6f4a51
        with:
          github_token: ${{ secrets.SYS_ORCH_GITHUB }}

permissions:
  contents: read
  pull-requests: write
