# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Update Auto-Merge PRs

# On push to the main branch, update any branches that are out of date and have auto-merge enabled. If the branch is
# currently out of date, it must be first manually updated and then will be kept up to date on future runs.
on:
  push:
    branches:
      - main

jobs:
  Auto-Update-Branch:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/auto-update@v2.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
