# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

name: Validate and Generate OpenAPI

on:
  pull_request:
    paths:
      - 'tenancy-api-mapping/**'

permissions:
  contents: read

jobs:
  check-generate:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594  # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          persist-credentials: false

      - name: Bootstrap CI environment
        uses: open-edge-platform/orch-ci/.github/actions/bootstrap@388f7e2aa884295786ed363fc97d3fd45e57e12a  # 2026.0.8
        with:
          gh_token: ${{ secrets.SYS_EMF_GH_TOKEN }}

      - name: Generate OpenAPI specs and combined spec
        run: |
          cd tenancy-api-mapping
          make gen-convert-combine-all

      - name: Check for changes
        run: |
          npm --version
          if [[ `git status --porcelain` ]]; then
            echo "### Error: Changes detected after running make gen-convert-combine-all"
            echo "### git status --porcelain"
            git status --porcelain
            echo "### git diff"
            git diff
            echo "### Error: Changes detected after running make gen-convert-combine-all" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "No changes detected - OpenAPI is up to date" >> $GITHUB_STEP_SUMMARY
          fi
