# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
name: Post-Merge Scorecard CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-scorecard:
    permissions:
      security-events: write   # required for SARIF upload
      id-token: write
      contents: read

    uses: open-edge-platform/orch-ci/.github/workflows/post-merge-scorecard.yml@1871595c6bb5f5f29b957725e9cbb05ef8071ca1  # 2026.1.3
    with:
      project_folder: "."
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
