# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ro-rootfs
  annotations:
    policies.kyverno.io/title: Require Read-Only Root Filesystem
    policies.kyverno.io/category: Best Practices, EKS Best Practices, PSP Migration
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      A read-only root file system helps to enforce an immutable infrastructure strategy;
      the container only needs to write on the mounted volume that persists the state.
      An immutable root filesystem can also prevent malicious binaries from writing to the
      host system. This policy validates that containers define a securityContext
      with `readOnlyRootFilesystem: true`.
spec:
  validationFailureAction: {{ .Values.require_ro_rootfs.FailureAction }}
  background: true
  rules:
  - name: validate-readOnlyRootFilesystem
    exclude:
      any:
      - resources:
          namespaces:
            - cert-manager
            - cattle-system
            - cattle-fleet-local-system
            - cattle-fleet-system
            - cattle-provisioning-capi-system
            - orch-app
            - orch-boots
            - orch-cluster
            - orch-database
            - orch-infra
            - orch-platform
            - orch-secret
            - orch-sre
            - orch-ui
            - metallb-system
            - local-path-storage
            - kube-system
            - fleet-default
      - resources:
          names:
            - "mp*"
            - "metal*"
            - "mi*"
            - "helm*"
            - "deploy*"
            - "capi*"
            - "git*"
            - "cert*"
            - "kube*"
            - "kind*"
            - "harbor*"
            - "secret*"
            - "ingress*"
            - "etcd*"
            - "rke2*"
            # rs-proxy needs to be able to write to the filesystem to store the certificates it generates.
            - "rs-proxy*"


    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Root filesystem must be read-only."
      pattern:
        spec:
          containers:
          - securityContext:
              readOnlyRootFilesystem: true
---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: licensing-exception-require-ro-rootfs
spec:
  exceptions:
  - policyName: require-ro-rootfs
    ruleNames:
    - validate-readOnlyRootFilesystem
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - orch-gateway
        names:
        - licensing-deployment*
