# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
global:
  localSubModsDir: "gitsubmodules"
  specOutputDir: "openapispecs/generated"
  apimappingconfigcrsdir: "apimappingconfigcrs"

  servers:
    - url: "{apiRoot}"
      variables:
        - key: "apiRoot"
          value: "https://<multitenancy-gateway-host>"
